version: "3"

services:
  gateway-db:
    image: postgres:12.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gateway-db
    ports:
      - 5445:5432
    volumes:
      - ./gateway-database:/var/lib/postgresql/data

  gateway-server:
    build: .
    command: sh -c "npm install && npm run start:dev"
    ports:
      - 4000:4000
    environment:
      POSTGRES_HOST: gateway-db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gateway-db
      JWT_SECRET: mychallenge2023
    working_dir: /home/node
    volumes:
      - .:/home/node
    depends_on:
      - rmq-service
      - gateway-db
    networks:
      - challenge-network

  adminer:
    image: adminer
    ports:
      - 8092:8080

  rmq-service:
    image: rabbitmq:3-management
    ports:
        - 5672:5672
        - 15672:15672
    networks:
        - challenge-network

networks:
  challenge-network:
    external: true