version: "3"

services:
  users-db:
    image: postgres:12.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users-db
    ports:
      - 5440:5432
    volumes:
      - ./database:/var/lib/postgresql/data
  users-server:
    build: .
    command: npm run start:dev
    restart: always
    ports:
      - 3008:3000
    environment:
      POSTGRES_HOST: users-db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users-db
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - users-db
  adminer:
    image: adminer
    restart: always
    ports:
      - 8087:8080