version: "3"

services:
  users-db:
    image: postgres:12.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users-db
    ports:
      - 5444:5432
    volumes:
      - ./users-database:/var/lib/postgresql/data
    networks:
      - challenge-network
  users-server:
    build: .
    command: sh -c "npm install && npm run start:dev"
    ports:
      - 3008:3000
    environment:
      POSTGRES_HOST: users-db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users-db
    working_dir: /home/node
    volumes:
      - .:/home/node
    depends_on:
      - users-db
    networks:
      - challenge-network
  adminer:
    image: adminer
    ports:
      - 8087:8080
    networks:
      - challenge-network
networks:
  challenge-network:
    external: true