version: "3"

services:
  database:
    image: postgres:12.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./database:/var/lib/postgresql/data
  server:
    image: node:19.0.0-alpine
    tty: true
    stdin_open: true
    working_dir: /home/node
    ports:
      - 3001:3001
    environment:
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - .:/home/node
