version: "3"

services:
  payments-db:
    image: postgres:12.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payments-db
    ports:
      - 5434:5432
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - challenge-network
  payments-server:
    build: .
    command: sh -c "npm install && npm run start:dev"
    ports:
      - 3002:3000
    environment:
      POSTGRES_HOST: payments-db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payments-db
      STRIPE_SECRET_KEY: sk_test_51IUL0ZLnExjIVJcojZq1EQ82kFJ7i5TN13Sh98VaK9yLX8R75ZOPVt08535LQFRTzW9hsNZDg9reWLhESeicdcTu00ak7gVZyY
      STRIPE_URL_FRONT: http://localhost:3000
    working_dir: /home/node
    volumes:
      - .:/home/node
    depends_on:
      - payments-db
    networks:
      - challenge-network

  adminer:
    image: adminer
    ports:
      - 8083:8080

networks:
  challenge-network:
    external: true
