version: "3"

services:
  database:
    image: postgres:12.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5438:5432
    volumes:
      - ./database:/var/lib/postgresql/data
  server:
    build: .
    ports:
      - 3006:3000
    environment:
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    # volumes:
    #   - ./server:/app
    depends_on:
      - database

