version: "3"

services:
  sellers-db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
    networks:
      - challenge-network
  sellers-server:
    build: .
    command: sh -c "npm install && npm run start:dev"
    restart: always
    ports:
      - 3006:3000
    environment:
      MONGO_URL: mongodb://sellers-db:27017/sellers-db
      POSTGRES_HOST: sellers-db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sellers-db
    working_dir: /home/node
    volumes:
      - .:/home/node
    depends_on:
      - sellers-db
    networks:
      - challenge-network
networks:
  challenge-network:
    external: true

