version: "3"

services:
  database:
    image: postgres:12.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5438:5432
    volumes:
      - ./database:/var/lib/postgresql/data
  server:
    build: .
    command: npm run start:dev
    restart: always
    ports:
      - 3006:3000
    environment:
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - database
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

