version: "3"

services:
  sellers-db:
    image: postgres:12.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sellers-db
    ports:
      - 5438:5432
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - challenge-network
  sellers-server:
    build: .
    command: sh -c "npm install && npm run start:dev"
    restart: always
    ports:
      - 3006:3000
    environment:
      POSTGRES_HOST: sellers-db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sellers-db
    working_dir: /home/node
    volumes:
      - .:/home/node
    depends_on:
      - sellers-db
    networks:
      - challenge-network
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
networks:
  challenge-network:
    external: true

