version: "3"

services:
  carrier-db:
    image: postgres:12.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: carrier-db
    ports:
      - 5413:5432
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - challenge-network      
  carrier-server:
    build: .
    command: npm run start:dev
    restart: always
    ports:
      - 3013:3000
    environment:
      POSTGRES_HOST: carrier-db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: carrier-db
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - carrier-db
    networks:
      - challenge-network    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8087:8080
networks:
  challenge-network:
    external: true    