apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge-users-db
spec:
  selector:
    matchLabels:
      app: challenge-users-db
  replicas: 1
  template:
    metadata:
      labels:
        app: challenge-users-db
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: challenge_users
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: challenge-users-db
spec:
  selector:
    app: challenge-users-db
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  clusterIP: None
