# deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge-users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: challenge-users
  template:
    metadata:
      labels:
        app: challenge-users
    spec:
      containers:
        - name: challenge-users
          image: yacinesoussi/challenges2-yacine-users
          ports:
            - containerPort: 3001
          env:
            - name: DB_HOST
              value: challenge-users-db
            - name: DB_NAME
              value: challenge_users
            - name: DB_USER
              value: user
            - name: DB_PASSWORD
              value: password

---

apiVersion: v1
kind: Service
metadata:
  name: challenge-users
  labels:
    app: challenge-users
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3001
    targetPort: 3001
  selector:
    app: challenge-users

---

apiVersion: v1
kind: Service
metadata:
  name: challenge-users-external
  labels:
    app: challenge-users
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 3001
    targetPort: 3001
  selector:
    app: challenge-users

