version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: returns_db
      POSTGRES_PASSWORD: returns_db
      POSTGRES_DB: returns_db
  app:
    build: .
    command: npm run start:dev
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  db_data: