version: "3"

services:
  returns-db:
    image: postgres:12.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: returns-db
    ports:
      - 5437:5432
    volumes:
      - ./database:/var/lib/postgresql/data
  returns-server:
    build: .
    ports:
      - 3005:3000
    environment:
      POSTGRES_HOST: returns-db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: returns-db
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - returns-db
  adminer:
    image: adminer
    restart: always
    ports:
      - 8084:8080
