version: "3"

services:
  returns-db:
    image: postgres:12.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: returns-db
    ports:
      - 5440:5432
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - challenge-network
  returns-server:
    restart: always
    build: .
    command: sh -c "npm install && npm run start:dev"
    ports:
      - 3005:3000
    environment:
      POSTGRES_HOST: returns-db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: returns-db
    working_dir: /home/node
    volumes:
      - .:/home/node
    depends_on:
      - returns-db
    networks:
      - challenge-network
  adminer:
    image: adminer
    restart: always
    ports:
      - 8084:8080
    networks:
      - challenge-network
networks:
  challenge-network:
    external: true
