version: "3"

services:
  orders-db:
    image: postgres:12.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orders-db
    ports:
      - 5433:5432
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - challenge-network  
  orders-server:
    build: .
    ports:
      - 3001:3000
    environment:
      POSTGRES_HOST: orders-db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orders-db
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - orders-db
    networks:
      - challenge-network  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8086:8080
networks:
  challenge-network:
    external: true
