version: "3"

services:
  images-db:
    image: postgres:12.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: images-db
    ports:
      - 5445:5432
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - challenge-network
  images-server:
    build: .
    command: sh -c "npm install && npm run start:dev"
    ports:
      - 3011:3000
    environment:
      POSTGRES_HOST: images-db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: images-db
    working_dir: /home/node
    volumes:
      - .:/home/node
    depends_on:
      - images-db
    networks:
      - challenge-network
  adminer:
    image: adminer
    ports:
      - 8093:8080
    networks:
      - challenge-network
networks:
  challenge-network:
    external: true
