apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge-mailer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: challenge-mailer
  template:
    metadata:
      labels:
        app: challenge-mailer
    spec:
      containers:
        - name: challenge-mailer
          image: yacinesoussi/challenges2-yacine-mailer:latest
          ports:
            - containerPort: 3000
          env:
            - name: EMAIL_SERVER
              value: "no-reply@moon-factory.fr"
            - name: EMAIL_PASSWORD
              value: "MoonFactory123$"
            - name: FRONT_URL
              value: "http://challenge-front-external"
            - name: RMQ_SERVICE_HOST
              value: 34.76.248.98

---

apiVersion: v1
kind: Service
metadata:
  name: challenge-mailer
  labels:
    app: challenge-mailer
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3009
    targetPort: 3000
  selector:
    app: challenge-mailer

