apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge-addresses-db
spec:
  selector:
    matchLabels:
      app: challenge-addresses-db
  replicas: 1
  template:
    metadata:
      labels:
        app: challenge-addresses-db
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: challenge-addresses-db
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-persistent-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-persistent-storage
          emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: challenge-addresses-db
spec:
  type: ClusterIP
  selector:
    app: challenge-addresses-db
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432