apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge-returns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: challenge-returns
  template:
    metadata:
      labels:
        app: challenge-returns
    spec:
      containers:
        - name: challenge-returns
          image: yacinesoussi/challenges2-yacine-returns:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
          env:
            - name: POSTGRES_DB
              value: challenge-returns-db
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_HOST
              value: challenge-returns-db
            - name: POSTGRES_PORT
              value: "5432"

---
apiVersion: v1
kind: Service
metadata:
  name: challenge-returns
  labels:
    app: challenge-returns
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3005
      targetPort: 3000
  selector:
    app: challenge-returns
