apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge-products
spec:
  selector:
    matchLabels:
      app: challenge-products
  replicas: 1
  template:
    metadata:
      labels:
        app: challenge-products
    spec:
      containers:
        - name: challenge-products
          image: yacinesoussi/challenges2-yacine-products:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
          env:
            - name: POSTGRES_DB
              value: challenge-products-db
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_HOST
              value: challenge-products-db
            - name: POSTGRES_PORT
              value: "5432"

---

apiVersion: v1
kind: Service
metadata:
  name: challenge-products
  labels:
    app: challenge-products
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3003
    targetPort: 3000
  selector:
    app: challenge-products