apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge-sellers-db
spec:
  selector:
    matchLabels:
      app: challenge-sellers-db
  replicas: 1
  template:
    metadata:
      labels:
        app: challenge-sellers-db
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-persistent-storage
              mountPath: /data/db
      volumes:
        - name: mongodb-persistent-storage
          emptyDir: {}
---

apiVersion: v1
kind: Service
metadata:
  name: challenge-sellers-db
spec:
  type: ClusterIP
  selector:
    app: challenge-sellers-db
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
