# deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge-users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: challenge-users
  template:
    metadata:
      labels:
        app: challenge-users
    spec:
      containers:
        - name: challenge-users
          image: yacinesoussi/challenges2-yacine-users:latest
          ports:
            - containerPort: 3001
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: POSTGRES_DB
              value: challenge-users-db
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_HOST
              value: challenge-users-db
            - name: POSTGRES_PORT
              value: "5432"
            - name: JWT_SECRET
              value: "my_big_secret"
            - name: RMQ_SERVICE_HOST
              value: 34.76.248.98

---

apiVersion: v1
kind: Service
metadata:
  name: challenge-users
  labels:
    app: challenge-users
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3001
    targetPort: 3001
  selector:
    app: challenge-users
