version: "3"

services:
  payments-db:
    image: postgres:12.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payments-db
    ports:
      - 5434:5432
    volumes:
      - ./database:/var/lib/postgresql/data
  payments-server:
    build: .
    command: npm run start:dev
    restart: always
    ports:
      - 3002:3000
    environment:
      POSTGRES_HOST: payments-db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payments-db
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - payments-db
  adminer:
    image: adminer
    restart: always
    ports:
      - 8083:8080
