version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: payments_db
      POSTGRES_PASSWORD: payments_db
      POSTGRES_DB: payments_db
  app:
    build: .
    command: npm run start:dev
    restart: always
    ports:
      - "3003:3000"
    depends_on:
      - db
volumes:
  db_data: