version: "3"

services:
  front-db:
    image: postgres:12.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: front-db
    ports:
      - 5432:5432
    volumes:
      - ./database:/var/lib/postgresql/data
  front-server:
    build: .
    ports:
      - 3000:3000
    environment:
      POSTGRES_HOST: front-db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: front-db
    networks:
      - challenge-network
    # volumes:
    #   - ./server:/app
    depends_on:
      - front-db
networks:
  challenge-network:
    external: true