version: '3'
services:
  server:
    image: node:19.0.0-alpine
    working_dir: /app
    build: 
      context: .
      dockerfile: Dockerfile
      target: app_dev
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    tty: true
    stdin_open: true
    command: sh -c "npm install && npm run start"
    environment:
      - REACT_APP_BASE_API_URL=${REACT_APP_BASE_API_URL}
      - REACT_APP_API_URL=${REACT_APP_API_URL}
      - REACT_APP_HOST=${REACT_APP_HOST}
    volumes:
      - .:/app
