version: "3"

services:
  server:
    image: node:19.0.0-alpine
    working_dir: /home/node
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    tty: true
    stdin_open: true
    command: sh -c "npm install && npm run start"
    volumes:
      - .:/home/node
    depends_on:
      - postgres

  postgres:
    image: postgres:13.3-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${DATABASE_URL}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./postgres:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:${ADMINER_PORT}
