version: '3'
services:
  server:
    image: node:19.0.0-alpine
    working_dir: /app
    build: .
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    tty: true
    stdin_open: true
    command: sh -c "npm install && npm run start"
    volumes:
      - .:/app
