version: "3"

services:
  address-db:
    image: postgres:12.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: address-db
    ports:
      - 5412:5432
    volumes:
      - ./database:/var/lib/postgresql/data
  address-server:
    build: .
    command: npm run start:dev
    restart: always
    ports:
      - 3012:3000
    environment:
      POSTGRES_HOST: users-db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: address-db
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - address-db
  adminer:
    image: adminer
    restart: always
    ports:
      - 8087:8080