name: CI/CD challenge front microservice

on:
  push:
    branches:
      - feature/deploy-test
    # paths:
    #   - "challenge-front/**"
    #   - ".github/workflows/challenge-front.yml"

env:
  GKE_CLUSTER: marketplace
  GKE_ZONE: europe-west1

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./challenge-front
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install
      # - name: Run tests
      #   run: npm run test
      - name: build
        run: npm run build

  publish-image:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./challenge-front
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/challenges2-yacine:latest
          args: |
            --build-arg REACT_APP_TOTO=1

  deploy:
    runs-on: ubuntu-latest
    needs: publish-image
    steps:
      - name: Set up Kubernetes
        uses: actions/checkout@v3

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}

      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}

      - name: Update deployment
        run: |
          kubectl patch deployment challenge-front -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}"
