name: CI/CD challenge payment microservice

on:
  push:
    branches:
      - feature/deploy-test
    # paths:
    #   - "challenge-payment/**"

env:
  GKE_CLUSTER: marketplace
  GKE_ZONE: europe-west1

jobs:
  test: 
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14.8-alpine3.17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/db_test
     
    defaults:
      run:
        working-directory: ./challenge-payment
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install
      # - name: Run tests
      #   run: npm run test
      - name: build
        run: npm run build
    
  publish-image:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push challenge-payment
        uses: docker/build-push-action@v2
        with:
          context: ./challenge-payment
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/challenge-payment:latest

    
  deploy:
    runs-on: ubuntu-latest
    needs: publish-image
    steps:
      - name: Set up Kubernetes
        uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}

      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
      
      - name: Set up Kustomize
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize

      - name: Update deployment
        run: |
          kubectl patch deployment challenge-gateway -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}"
    
