name: Publish Docker image

on:
  push:
    branches:
      - main
env:
  GKE_CLUSTER: marketplace
  GKE_ZONE: europe-west1

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build and test challenge-front
        run: |
          cd challenge-front
          npm install
          npm run build
      - name: Build and test challenge-users
        run: |
          cd challenge-users
          npm install
          npm run build
      - name: Build and test challenge-gateway
        run: |
          cd challenge-gateway
          npm install
          npm run build
      - name: Build and test challenge-mailer
        run: |
          cd challenge-mailer
          npm install
          npm run build

  publish-docker:
    runs-on: ubuntu-latest

    needs: build-test

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push challenge-front
        # if: ${{ github.event_name == 'push' && contains(github.event.head_commit.modified, 'challenge-front/') }}
        uses: docker/build-push-action@v2
        with:
          context: ./challenge-front
          file: ./challenge-front/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/challenges2-yacine:latest
      
      - name: Build and push challenge-users
        # if: ${{ github.event_name == 'push' && contains(github.event.head_commit.modified, 'challenge-users/') }}
        uses: docker/build-push-action@v2
        with:
          context: ./challenge-users
          file: ./challenge-users/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/challenges2-yacine-users:latest
      
      - name: Build and push challenge-gateway
        # if: ${{ github.event_name == 'push' && contains(github.event.head_commit.modified, 'challenge-gateway/') }}
        uses: docker/build-push-action@v2
        with:
          context: ./challenge-gateway
          file: ./challenge-gateway/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/challenges2-yacine-gateway:latest
      
      - name: Build and push challenge-mailer
        # if: ${{ github.event_name == 'push' && contains(github.event.head_commit.modified, 'challenge-mailer/') }}
        uses: docker/build-push-action@v2
        with:
          context: ./challenge-mailer
          file: ./challenge-mailer/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/challenges2-yacine-mailer:latest

      - name: Build and push challenge-orders
        # if: ${{ github.event_name == 'push' && contains(github.event.head_commit.modified, 'challenge-orders/') }}
        uses: docker/build-push-action@v2
        with:
          context: ./challenge-orders
          file: ./challenge-orders/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/challenges2-yacine-orders:latest

      - name: Build and push challenge-products
        # if: ${{ github.event_name == 'push' && contains(github.event.head_commit.modified, 'challenge-products/') }}
        uses: docker/build-push-action@v2
        with:
          context: ./challenge-products
          file: ./challenge-products/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/challenges2-yacine-products:latest
      
      - name: Build and push challenge-payments
        # if: ${{ github.event_name == 'push' && contains(github.event.head_commit.modified, 'challenge-payments/') }}
        uses: docker/build-push-action@v2
        with:
          context: ./challenge-payments
          file: ./challenge-payments/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/challenges2-yacine-payments:latest
      
      - name: Build and push challenge-sellers
        # if: ${{ github.event_name == 'push' && contains(github.event.head_commit.modified, 'challenge-sellers/') }}
        uses: docker/build-push-action@v2
        with:
          context: ./challenge-sellers
          file: ./challenge-sellers/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/challenges2-yacine-sellers:latest

      - name: Build and push challenge-returns
        # if: ${{ github.event_name == 'push' && contains(github.event.head_commit.modified, 'challenge-returns/') }}
        uses: docker/build-push-action@v2
        with:
          context: ./challenge-returns
          file: ./challenge-returns/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/challenges2-yacine-returns:latest
      
  deploy-kubernetes:
    runs-on: ubuntu-latest
    needs: publish-docker
    steps:
      - name: Set up Kubernetes
        uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}

      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ secrets.GKE_SA_KEY }}

      - name: Set up Kustomize
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize

      - name: Deploy challenge-front
        run: |
          kubectl patch deployment challenge-front -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}"

      - name: Deploy challenge-users
        run: |
          kubectl patch deployment challenge-users -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}"
      
      - name: Deploy challenge-gateway
        run: |
          kubectl patch deployment challenge-gateway -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}"
      
      - name: Deploy challenge-mailer
        run: |
          kubectl patch deployment challenge-mailer -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}"
      
      - name: Deploy challenge-orders
        run: |
          kubectl patch deployment challenge-orders -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}"
      
      - name: Deploy challenge-products
        run: |
          kubectl patch deployment challenge-products -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}"
      
      - name: Deploy challenge-sellers
        run: |
          kubectl patch deployment challenge-sellers -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}"