name: Publish Docker image

on:
  push:
    branches:
      - test-kub

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get changed directories
        id: get_changeset
        uses: docker/get-changed-files@v1
        with:
          format: paths
      - name: Build and test challenge-front
        if: "contains(fromJson(steps.get_changeset.outputs.json).paths, 'challenge-front/')"
        run: |
          cd challenge-front
          npm install
          npm run build
      - name: Build and test challenge-users
        if: "contains(fromJson(steps.get_changeset.outputs.json).paths, 'challenge-users/')"
        run: |
          cd challenge-users
          npm install
          npm run build

  publish-docker:
    runs-on: ubuntu-latest

    needs: build-test

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push challenge-front
        if: "contains(fromJson(needs.build-test.outputs.get_changeset.outputs.json).paths, 'challenge-front/')"
        uses: docker/build-push-action@v2
        with:
          context: ./challenge-front
          file: ./challenge-front/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/challenges2-yacine:latest
      
      - name: Build and push challenge-users
        if: "contains(fromJson(needs.build-test.outputs.get_changeset.outputs.json).paths, 'challenge-users/')"
        uses: docker/build-push-action@v2
        with:
          context: ./challenge-users
          file: ./challenge-users/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/challenges2-yacine-users:latest
