name: Publish Docker image

on:
  push:
    branches:
      - test-kub

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check for changes
        id: check_for_changes
        run: |
          changed_files=$(git diff --name-only HEAD)
          echo "::set-output name=changed_files::$changed_files"

      - name: Build and test challenge-front
        if: ${{ contains(fromJSON(steps.check_for_changes.outputs.changed_files), 'challenge-front/') }}
        run: |
          cd challenge-front
          npm install
          npm run build

      - name: Build and test challenge-users
        if: ${{ contains(fromJSON(steps.check_for_changes.outputs.changed_files), 'challenge-users/') }}
        run: |
          cd challenge-users
          npm install
          npm run build

  publish-docker:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push challenge-front
        if: ${{ contains(fromJSON(needs.build-test.outputs.check_for_changes), 'challenge-front/') }}
        uses: docker/build-push-action@v2
        with:
          context: ./challenge-front
          file: ./challenge-front/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/challenges2-yacine:latest
      
      - name: Build and push challenge-users
        if: ${{ contains(fromJSON(needs.build-test.outputs.check_for_changes), 'challenge-users/') }}
        uses: docker/build-push-action@v2
        with:
          context: ./challenge-users
          file: ./challenge-users/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/challenges2-yacine-users:latest
