name: Build, Push, and Deploy

on:
  push:
    branches: [ "feat/test-gcp" ]

env:
  PROJECT_ID: challenge-383612
  IMAGE_NAME: challenge-users
  IMAGE_TAG: latest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
          service_account: '740146592006-compute@developer.gserviceaccount.com'
      - name: Push image to Google Container Registry
        run: |
          docker build ./challenge-users/ --file challenge-users/Dockerfile --tag gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} && docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}